namespace Inverter.GoodWe.PowerStationData
{
    internal class Invert_Full
    {
        public string sn { get; set; }
        public string powerstation_id { get; set; }
        public string name { get; set; }
        public string model_type { get; set; }
        public int change_type { get; set; }
        public int change_time { get; set; }
        public float capacity { get; set; }
        public float eday { get; set; }
        public float iday { get; set; }
        public float etotal { get; set; }
        public float itotal { get; set; }
        public float hour_total { get; set; }
        public int status { get; set; }
        public long turnon_time { get; set; }
        public float pac { get; set; }
        public float tempperature { get; set; }
        public float vpv1 { get; set; }
        public float vpv2 { get; set; }
        public float vpv3 { get; set; }
        public float vpv4 { get; set; }
        public float ipv1 { get; set; }
        public float ipv2 { get; set; }
        public float ipv3 { get; set; }
        public float ipv4 { get; set; }
        public float vac1 { get; set; }
        public float vac2 { get; set; }
        public float vac3 { get; set; }
        public float iac1 { get; set; }
        public float iac2 { get; set; }
        public float iac3 { get; set; }
        public float fac1 { get; set; }
        public float fac2 { get; set; }
        public float fac3 { get; set; }
        public float istr1 { get; set; }
        public float istr2 { get; set; }
        public float istr3 { get; set; }
        public float istr4 { get; set; }
        public float istr5 { get; set; }
        public float istr6 { get; set; }
        public float istr7 { get; set; }
        public float istr8 { get; set; }
        public float istr9 { get; set; }
        public float istr10 { get; set; }
        public float istr11 { get; set; }
        public float istr12 { get; set; }
        public float istr13 { get; set; }
        public float istr14 { get; set; }
        public float istr15 { get; set; }
        public float istr16 { get; set; }
        public long last_time { get; set; }
        public float vbattery1 { get; set; }
        public float ibattery1 { get; set; }
        public float pmeter { get; set; }
        public float soc { get; set; }
        public float soh { get; set; }
        public object bms_discharge_i_max { get; set; }
        public float bms_charge_i_max { get; set; }
        public int bms_warning { get; set; }
        public int bms_alarm { get; set; }
        public int battary_work_mode { get; set; }
        public int workmode { get; set; }
        public float vload { get; set; }
        public float iload { get; set; }
        public float firmwareversion { get; set; }
        public float pbackup { get; set; }
        public float seller { get; set; }
        public float buy { get; set; }
        public object yesterdaybuytotal { get; set; }
        public object yesterdaysellertotal { get; set; }
        public object yesterdayct2sellertotal { get; set; }
        public object yesterdayetotal { get; set; }
        public object yesterdayetotalload { get; set; }
        public object thismonthetotle { get; set; }
        public float lastmonthetotle { get; set; }
        public float ram { get; set; }
        public float outputpower { get; set; }
        public float fault_messge { get; set; }
        public bool isbuettey { get; set; }
        public bool isbuetteybps { get; set; }
        public bool isbuetteybpu { get; set; }
        public bool isESUOREMU { get; set; }
        public object backUpPload_S { get; set; }
        public object backUpVload_S { get; set; }
        public object backUpIload_S { get; set; }
        public object backUpPload_T { get; set; }
        public object backUpVload_T { get; set; }
        public object backUpIload_T { get; set; }
        public object eTotalBuy { get; set; }
        public object eDayBuy { get; set; }
        public object eBatteryCharge { get; set; }
        public object eChargeDay { get; set; }
        public object eBatteryDischarge { get; set; }
        public object eDischargeDay { get; set; }
        public object battStrings { get; set; }
        public object meterConnectStatus { get; set; }
        public object mtActivepowerR { get; set; }
        public object mtActivepowerS { get; set; }
        public object mtActivepowerT { get; set; }
        public string dataloggersn { get; set; }
        public object equipment_name { get; set; }
        public bool hasmeter { get; set; }
        public object meter_type { get; set; }
        public object pre_hour_lasttotal { get; set; }
        public object pre_hour_time { get; set; }
        public object current_hour_pv { get; set; }
    }
}